<?php

// TWITTER CREDENTIALS – NEVER PLACE THIS FILE IN A PUBLIC LOCATION!
// Get yours from: https://apps.twitter.com/
// Note: You must replace the Xs with your own credentials before you can tweet.

$consumerKey = "XXXXXXXXXXXXXXXXXXXXXXXXX";
$consumerSecret = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
$accessToken = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
$accessTokenSecret = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
